### ISSUE TITLE
Document how to use and configure jqa-rdbms-plugin from maven pom

### ISSUE THREAD

**Issue by murdos** [buschmais/jqa-rdbms-plugin#6]
### Feature Description
 
I would like to run the RDBMS plugin with the jqassistant maven plugin, however I can't figure who to make it work.
https://stackoverflow.com/questions/62259763/integrate-jqassistant-maven-plugin-with-database-analysis-via-rdbms-plugin suggested this should be supported.

I can't figure if connection properties should be added in `<scanProperties>`  section of jqassistant maven plugin configuration, or as plain properties in `<properties>` section, if the `<scanIncludes>` section should comport a specific configuration, ...

Thanks in advance!

**Comment by StephanPirnbaum** [comment]
Continued at https://github.com/jqassistant-plugin/jqassistant-rdbms-plugin/issues/3
